from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from hunt_chain_recon.models.attack_surface import AttackSurface
from hunt_chain_recon.output.json_writer import JSONOutputWriter
from hunt_chain_recon.output.report import ReconReportGenerator


class OutputManagerError(Exception):
    """Raised when an output artifact cannot be generated."""


@dataclass(frozen=True)
class OutputResult:
    """Paths generated by the Project 2 output layer."""

    json_path: Path | None = None
    report_path: Path | None = None


class OutputManager:
    """Coordinate Project 2 JSON and human-readable output generation."""

    def __init__(
        self,
        json_writer: JSONOutputWriter | None = None,
        report_generator: ReconReportGenerator | None = None,
    ) -> None:
        self.json_writer = (
            json_writer
            if json_writer is not None
            else JSONOutputWriter()
        )

        self.report_generator = (
            report_generator
            if report_generator is not None
            else ReconReportGenerator()
        )

    def write(
        self,
        attack_surface: AttackSurface,
        output_directory: str | Path,
        *,
        json_enabled: bool = True,
        report_enabled: bool = True,
    ) -> OutputResult:
        """Generate the requested Project 2 output artifacts."""

        if not isinstance(attack_surface, AttackSurface):
            raise TypeError("Expected AttackSurface instance")

        if not json_enabled and not report_enabled:
            raise ValueError(
                "At least one output format must be enabled"
            )

        output_directory = Path(output_directory)

        try:
            output_directory.mkdir(
                parents=True,
                exist_ok=True,
            )
        except OSError as exc:
            raise OutputManagerError(
                f"Failed to create output directory: "
                f"{output_directory}"
            ) from exc

        json_path: Path | None = None
        report_path: Path | None = None

        if json_enabled:
            json_path = output_directory / "attack_surface.json"

            try:
                self.json_writer.write(
                    attack_surface,
                    json_path,
                )
            except Exception as exc:
                raise OutputManagerError(
                    "Failed to generate JSON output: "
                    f"{json_path}"
                ) from exc

        if report_enabled:
            report_path = output_directory / "recon_report.txt"

            try:
                self.report_generator.write(
                    attack_surface,
                    report_path,
                )
            except Exception as exc:
                raise OutputManagerError(
                    "Failed to generate human-readable report: "
                    f"{report_path}"
                ) from exc

        return OutputResult(
            json_path=json_path,
            report_path=report_path,
        )